"""health record refactor


Revision ID: 17ccee003c1a
Revises: 53b02f9426a2

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17ccee003c1a'
down_revision: Union[str, None] = '53b02f9426a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heart_rate_sample',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hr_sample_device_time', 'heart_rate_sample', ['device_id', 'recorded_at'], unique=False)
    op.create_table('step_sample',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_step_sample_device_time', 'step_sample', ['device_id', 'recorded_at'], unique=False)
    op.create_table('health_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heart_rate_min', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('heart_rate_max', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('heart_rate_avg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('steps_min', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('steps_max', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('steps_avg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_health_record_time', 'health_record', ['user_id', 'start_datetime', 'end_datetime'], unique=False)
    op.create_index('idx_health_record_user_category', 'health_record', ['user_id', 'category'], unique=False)
    op.drop_table('workoutstatistic')
    op.drop_table('workout')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.Column('source_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('start_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='workout_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='workout_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('workoutstatistic',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workout_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('min', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('max', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('avg', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('start_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('workoutstatistic_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name=op.f('workoutstatistic_workout_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workoutstatistic_pkey'))
    )
    op.drop_index('idx_health_record_user_category', table_name='health_record')
    op.drop_index('idx_health_record_time', table_name='health_record')
    op.drop_table('health_record')
    op.drop_index('idx_step_sample_device_time', table_name='step_sample')
    op.drop_table('step_sample')
    op.drop_index('idx_hr_sample_device_time', table_name='heart_rate_sample')
    op.drop_table('heart_rate_sample')
    # ### end Alembic commands ###
